#!/usr/bin/env python3
"""Regenerate docs/AGENT_INDEX.md — the navigation map the routines read.

An agent studying one tab should read that file and go straight to the handful
of files that matter, instead of searching 1,200 tracked files. Keeping it
generated rather than hand-written is the point: docs/DATA_PLATFORM_MAP.md went
four months stale, and a stale index is worse than none because it sends agents
to the wrong place confidently.

Run from the repo root:  python3 backend/scripts/build_agent_index.py
"""
import os
import re

OUT = "docs/AGENT_INDEX.md"

# Tab label -> the directories its code actually lives in. Note that Freight and
# COT keep their components inside frontend/app/, not frontend/components/.
TABS = [
    ("Futures Exchange", ["frontend/app/futures", "frontend/components/futures"]),
    ("News",             ["frontend/app/news", "frontend/components/news"]),
    ("COT",              ["frontend/app/cot", "frontend/app/signals", "frontend/components/signals"]),
    ("Freight",          ["frontend/app/freight"]),
    ("Supply",           ["frontend/app/supply", "frontend/components/supply"]),
    ("Demand",           ["frontend/app/demand", "frontend/components/demand"]),
    ("Macro",            ["frontend/app/macro", "frontend/components/macro"]),
    ("Map",              ["frontend/app/map", "frontend/components/map"]),
    ("Data Map",         ["frontend/app/data-map", "frontend/components/data-map"]),
    ("Research",         ["frontend/app/research", "frontend/components/research"]),
]

DATA_REF = re.compile(r"/data/([A-Za-z0-9_\-.]+\.json)")
SUPPLY_TABS = re.compile(r'\{\s*id:\s*"([a-z0-9_-]+)"', re.I)


def scan(dirs):
    """Count .ts/.tsx files under dirs and collect the /data/*.json they reference."""
    n, data = 0, set()
    for d in dirs:
        if not os.path.isdir(d):
            continue
        for root, _, files in os.walk(d):
            for f in files:
                if not f.endswith((".ts", ".tsx")):
                    continue
                n += 1
                try:
                    text = open(os.path.join(root, f), encoding="utf-8").read()
                except OSError:
                    continue
                data.update(DATA_REF.findall(text))
    return n, sorted(data)


def supply_subtabs():
    """The Supply sub-tab order, read from the page rather than hard-coded."""
    try:
        src = open("frontend/app/supply/page.tsx", encoding="utf-8").read()
    except OSError:
        return []
    block = src.split("const TABS", 1)
    return SUPPLY_TABS.findall(block[1].split("]", 1)[0]) if len(block) > 1 else []


def main():
    out = []
    out.append("# Agent index — where things live\n")
    out.append("_Generated by `backend/scripts/build_agent_index.py`. Purpose: an agent studying one")
    out.append("tab should read THIS file and go straight to the handful of files that matter,")
    out.append("instead of searching 1,200 tracked files. Regenerate when tabs or data files change._\n")
    out.append("| Tab | Where the code is | Files | Data it reads |")
    out.append("|-----|-------------------|------:|---------------|")
    for label, dirs in TABS:
        n, data = scan(dirs)
        where = " · ".join(f"`{d}/`" for d in dirs)
        shown = ", ".join(f"`{x}`" for x in data[:8]) or "—"
        if len(data) > 8:
            shown += f" _+{len(data) - 8} more_"
        out.append(f"| **{label}** | {where} | {n} | {shown} |")

    subs = supply_subtabs()
    out.append("\n## Supply sub-tabs (Tuesday rota, in page order)\n")
    out.append(f"Defined as `TABS` in `frontend/app/supply/page.tsx`. **{len(subs)}** of them:\n")
    out.append("`" + " → ".join(subs) + "` → back to the start\n")
    out.append("Each maps to a component under `frontend/components/supply/` — e.g. `sd` →")
    out.append("`SupplySDTab.tsx`, `brazil` → `BrazilTab/`, `fertilizers` → `FertilizersTab.tsx`.\n")

    out.append("## Where the rest lives\n")
    out.append("| Thing | Path |")
    out.append("|-------|------|")
    for thing, path in [
        ("Scrapers", "`backend/scraper/sources/`"),
        ("Exporters (write the JSON)", "`backend/scraper/export_static_json.py`, `backend/scraper/exports/`"),
        ("One-off scripts", "`backend/scripts/`"),
        ("Published data", "`frontend/public/data/*.json`"),
        ("Workflows", "`.github/workflows/*.yml`"),
        ("Pipeline health stamps", "`frontend/public/data/health.json`"),
        ("Source detection state", "`data/source_sentinels.json`"),
        ("7-day Actions run record", "`frontend/public/data/workflow_activity.json`"),
        ("Open health issues / work queue", "`ACTIONS_ISSUES.md`"),
        ("Improvement backlog + rota", "`IMPROVEMENTS.md`"),
        ("Architecture narrative", "`docs/DATA_PLATFORM_MAP.md` (long, hand-written)"),
    ]:
        out.append(f"| {thing} | {path} |")

    out.append("\n## Reading these cheaply\n")
    out.append("`workflow_activity.json` is 26 KB and `workflows_inventory.json` is 38 KB. Reading both")
    out.append("into context costs roughly 16,000 tokens to learn facts a one-line query answers in 150.")
    out.append("Query them; do not open them:\n")
    out.append("```sh")
    out.append("python3 -c \"import json; d=json.load(open('frontend/public/data/workflow_activity.json')); \\")
    out.append("print([(w['name'], w['failure'], w['runs']) for w in d['workflows'] if w['failure']])\"")
    out.append("```")

    os.makedirs(os.path.dirname(OUT), exist_ok=True)
    with open(OUT, "w", encoding="utf-8") as fh:
        fh.write("\n".join(out) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
