// Article catalogue for the Research tab — ONE row per published article.
//
// Generated 2026-08-21 by walking ResearchView.tsx's render blocks and the
// card shells (Paper / ResearchCard / CollapsibleCard) inside every component
// they mount. Until now the 45 articles existed only as hardcoded JSX, which
// is why nothing could search, sort, re-order or re-categorise them — there
// was no list to operate on.
//
// `body` names the React component that renders the article; the catalogue
// carries only the metadata around it, so live charts stay live.
export type Cat = "quant" | "supply" | "logistics" | "exchange" | "demand" | "admin";
export type Tone = "amber" | "sky" | "violet" | "emerald" | "indigo" | "rose" | "slate";

export interface Article {
  id: string;            // stable slug — the key admin overrides are stored against
  cat: Cat;
  title: string;
  subtitle: string | null;
  kicker: string | null;
  tone: string | null;
  updated: string | null;  // YYYY-MM-DD, null where the source card carries no date
  /** YYYY-MM-DD the article first went live, or null where it is NOT KNOWN.
   *
   *  Recovered from git: the first commit introducing the article's body
   *  component. That only works back to the repository's own first commit,
   *  2026-08-08 — 33 of the 49 articles already existed by then, and for those
   *  the first-appearance date is the import, not the publication. Those are
   *  null rather than stamped 2026-08-08, because a precise-looking wrong date
   *  is worse than an absent one: it would sort a two-year-old note in among
   *  last week's.
   *
   *  Null means unknown, never "oldest" — see `sortArticles`, which keeps
   *  unknowns at the bottom in BOTH directions.
   *
   *  Note this is the date the work went live, so it can fall a day after
   *  `updated`, which is the date written on the article itself. */
  published: string | null;
  body: string | null;     // component name that renders the content
}

export const CAT_LABEL: Record<Cat, string> = {
  quant:     "Quant & positioning",
  supply:    "Supply",
  logistics: "Logistics",
  exchange:  "Exchange & certified stocks",
  demand:    "Demand",
  admin:     "Admin & platform",
};

export const ARTICLES: Article[] = [
  { id: "threshold-alerts-tell-me-when", cat: "admin", title: "Threshold alerts — tell me when", subtitle: "The rules that page the admin channel when a published number crosses a line, what each is watching now, and whether it is armed", kicker: "Platform · alerting", tone: "slate", updated: "2026-09-03", published: "2026-09-03", body: "ThresholdAlerts" },
  { id: "when-ice-publishes-the-robusta-stock-report", cat: "admin", title: "When ICE publishes the robusta stock report", subtitle: "56 observed publish seconds, and what they cost us to guess \u2014 the distribution behind workflow 1.13's runtime", kicker: "Platform \u00b7 scraper economics", tone: "slate", updated: "2026-09-04", published: "2026-08-26", body: "IcePublishTimes" },
  { id: "are-swap-dealers-commercials-or-speculators", cat: "quant", title: "Are swap dealers commercials or speculators?", subtitle: "Three behavioural tests on the disaggregated COT — both contracts, long and short legs kept separate", kicker: "COT · cohort identity", tone: "amber", updated: "2026-08-14", published: "2026-08-15", body: "CotSwapIdentity" },
  { id: "intraweek-cot-nowcast-methodology", cat: "quant", title: "Intraweek COT nowcast — methodology", subtitle: "Bridging the weekly COT report with a daily positioning estimate", kicker: "COT · positioning", tone: "amber", updated: "2026-07-14", published: null, body: "IntraweekMethodology" },
  { id: "cot-backtest-report", cat: "quant", title: "COT backtest report", subtitle: "Walk-forward backtest of the intraweek positioning model", kicker: "COT · positioning", tone: "amber", updated: "2026-07-14", published: null, body: "CotBacktestReport" },
  { id: "september-x-ray-kc-september-positioning-via-the-old", cat: "quant", title: "September X-ray — KC September positioning via the old-crop bucket", subtitle: "Once July trades out, the CFTC 'old crop' split shows the September contract's exact cohort positioning — compared against past Septembers", kicker: "COT · single-contract X-ray", tone: "amber", updated: "2026-07-22", published: null, body: "SeptemberXray" },
  { id: "crop-year-x-ray-the-same-trick-across-seven-cftc-mar", cat: "quant", title: "Crop-year X-ray — the same trick across seven CFTC markets", subtitle: "Cocoa, sugar, cotton, wheat, corn and soybeans carry the same old-crop split — single-contract positioning on each market's own crop calendar", kicker: "COT · cross-commodity", tone: "amber", updated: "2026-07-22", published: null, body: "CropyearXray" },
  { id: "signals-forecasts-the-four-models-behind-the-tab", cat: "quant", title: "Signals & forecasts — the four models behind the tab", subtitle: "Two live statistical/LLM models and two illustrative ML scaffolds", kicker: "Signals · Methodology", tone: "sky", updated: "2026-07-14", published: null, body: "SignalsMethodology" },
  { id: "open-price-direction-walk-forward-record", cat: "quant", title: "Open-price-direction — walk-forward record", subtitle: "Prediction vs. reality, out-of-sample", kicker: "Signals · track record", tone: "sky", updated: "2026-07-14", published: null, body: "OpenDirectionRecord" },
  { id: "the-harvest-last-hour-a-pre-hedging-signal-on-its-ow", cat: "quant", title: "The harvest last hour — a pre-hedging signal on its own horizon", subtitle: "NY's last hour predicts the next session's post-open drift, but only during Brazil harvest: the sign rule, the placebos that could have killed it, and the discovery caveat", kicker: "Signals · intraday", tone: "violet", updated: "2026-08-19", published: "2026-08-20", body: "IntradayDrift" },
  { id: "news-sentiment-turning-headlines-into-a-coffee-signa", cat: "quant", title: "News & sentiment — turning headlines into a coffee signal", subtitle: "How to read the LLM sentiment score, and how to trade with (and around) it", kicker: "Signals · Applied", tone: "rose", updated: "2026-07-14", published: null, body: "NewsSentimentMethodology" },
  { id: "futures-analytics-contract-math-roll-dynamics-the-pr", cat: "quant", title: "Futures analytics — contract math, roll dynamics & the pricelist engine", subtitle: "The calendar, OI-to-FND, live arbitrage and the Quotation flat-price model", kicker: "Futures · Methodology", tone: "violet", updated: "2026-07-14", published: null, body: "FuturesMethodology" },
  { id: "macro-fx-the-currency-index-and-cross-commodity-posi", cat: "quant", title: "Macro & FX — the currency index and cross-commodity positioning", subtitle: "The Coffee Currency Index, FX framing, and the macro-COT exposure & attribution model", kicker: "Macro · Methodology", tone: "emerald", updated: "2026-07-14", published: null, body: "MacroMethodology" },
  { id: "cpi-decoded-us-cpi-vs-eurozone-hicp", cat: "quant", title: "CPI, decoded — US CPI vs Eurozone HICP", subtitle: "How each index is actually built, where European countries genuinely differ, what gets published at what detail — and the coffee series hiding inside both", kicker: "Macro · CPI", tone: "emerald", updated: "2026-08-09", published: "2026-08-09", body: "CpiMethodology" },
  { id: "supply-modelling-production-estimates-balance-sheets", cat: "supply", title: "Supply modelling — production estimates, balance sheets & export nowcasts", subtitle: "How the app turns USDA, CONAB, CECAFE and customs data into a forward view", kicker: "Supply · Methodology", tone: "lime", updated: "2026-07-14", published: null, body: "SupplyMethodology" },
  { id: "farmer-economics-cost-of-production-break-even-crop-", cat: "supply", title: "Farmer economics — cost of production, break-even & crop stress", subtitle: "What it costs to grow a bag, the margin, and the agronomic-stress models that move yield", kicker: "Farmer economics · Methodology", tone: "orange", updated: "2026-07-14", published: null, body: "FarmerMethodology" },
  { id: "fertilizer-why-it-s-a-coffee-signal", cat: "supply", title: "Fertilizer — why it's a coffee signal", subtitle: "The largest cash input: short-term cost-push, medium-term yield lever", kicker: "Fertilizer · input cost", tone: "teal", updated: "2026-07-14", published: null, body: "FertilizerMethodology" },
  { id: "when-does-rain-become-a-supply-shock", cat: "supply", title: "When does rain become a supply shock?", subtitle: "Phenology windows: when rainfall matters, and when it doesn't", kicker: "Agronomy · Supply Risk", tone: null, updated: null, published: null, body: "AgronomyArticles" },
  { id: "which-clones-ship-when-and-how-much", cat: "supply", title: "Which clones ship when, and how much?", subtitle: "Vietnamese clone calendar — harvest timing and screen-size yield by variety", kicker: "Agronomy · Varieties", tone: null, updated: null, published: null, body: "AgronomyArticles" },
  { id: "what-does-a-kilo-of-robusta-actually-cost-to-grow", cat: "supply", title: "What does a kilo of Robusta actually cost to grow?", subtitle: "Farm production-cost stack and the farmgate break-even", kicker: "Agronomy · Production Costs", tone: null, updated: null, published: null, body: "AgronomyArticles" },
  { id: "how-fragile-is-vietnamese-supply-long-term", cat: "supply", title: "How fragile is Vietnamese supply long-term?", subtitle: "Ageing trees, water stress and land competition as slow structural risks", kicker: "Agronomy · Long-term Risk", tone: null, updated: null, published: null, body: "AgronomyArticles" },
  { id: "npk-urea-and-map-why-agronomists-and-traders-speak-d", cat: "supply", title: "NPK, Urea and MAP: why agronomists and traders speak different languages", subtitle: "Translating fertilizer market tickers into field application reality", kicker: "Agronomy · Fertilizer Fundamentals", tone: null, updated: null, published: null, body: "AgronomyArticles" },
  { id: "enso-el-ni-o-interactive-explainer", cat: "supply", title: "ENSO / El Niño — interactive explainer", subtitle: "Ocean–atmosphere simulation of the El Niño / La Niña cycle", kicker: "Weather · ENSO", tone: "cyan", updated: "2026-07-14", published: null, body: "EnsoExplainer" },
  { id: "the-enso-risk-model-from-oni-to-per-origin-coffee-ri", cat: "supply", title: "The ENSO risk model — from ONI to per-origin coffee risk", subtitle: "How the app quantifies the cycle the explainer above describes", kicker: "Weather · ENSO model", tone: "cyan", updated: "2026-07-14", published: null, body: "EnsoModelMethodology" },
  { id: "drought-risk-how-the-spi-spei-vhi-stack-works", cat: "supply", title: "Drought risk — how the SPI / SPEI / VHI stack works", subtitle: "30-year calibrated SPI/SPEI z-scores, satellite cross-checks, and the backtested v3 alert ladder that decides when dryness becomes a market signal", kicker: "Weather · drought model", tone: "cyan", updated: "2026-07-30", published: null, body: "DroughtRiskMethodology" },
  { id: "theoretical-yield-vs-rainfall-theory-29-harvests-and", cat: "supply", title: "Theoretical yield vs rainfall — theory, 29 harvests, and the live year", subtitle: "Literature-calibrated rain→yield curves (WCR/Embrapa/Cenicafé) overlaid with USDA production reality per origin, plus the running crop-year projection", kicker: "Weather · yield model", tone: "cyan", updated: "2026-07-30", published: null, body: "YieldRainfall" },
  { id: "frost-risk-why-radiative-frost-is-the-trade-that-mat", cat: "supply", title: "Frost risk — why radiative frost is the trade that matters", subtitle: "The physics of Brazilian winter frost and how the monitor flags it", kicker: "Weather · tail risk", tone: "cyan", updated: "2026-07-14", published: null, body: "FrostRiskMethodology" },
  { id: "origin-logistics-the-fobbing-cost-model", cat: "logistics", title: "Origin logistics — the FOBbing cost model", subtitle: "Farm-to-vessel cost stack by origin — fixed block + ad-valorem share, repriced daily", kicker: "Logistics · origin", tone: "emerald", updated: "2026-08-12", published: null, body: "OriginLogistics" },
  { id: "destination-in-store-cost", cat: "logistics", title: "Destination in-store cost", subtitle: "CIF → in-store cost & financing, live in USD off today's FAQ price and EUR/USD", kicker: "Logistics · destination", tone: "sky", updated: "2026-07-14", published: null, body: "DestinationInstore" },
  { id: "freight-port-activity-how-the-numbers-are-built", cat: "logistics", title: "Freight & port activity — how the numbers are built", subtitle: "Container route estimates, the dry-bulk fertilizer proxy, and satellite port throughput", kicker: "Freight · Methodology", tone: "violet", updated: "2026-07-14", published: null, body: "FreightMethodology" },
  { id: "the-differential-model-a-research-note", cat: "exchange", title: "The Differential Model — a research note", subtitle: "Formalizing the full factor map — supply, demand, exchange economics and positioning — into one estimable model of an origin's differential", kicker: "Differential · model specification", tone: "sky", updated: "2026-08-10", published: "2026-08-10", body: "DifferentialModelNote" },
  { id: "certified-stocks-cohort-flow-methodology", cat: "exchange", title: "Certified stocks — cohort flow methodology", subtitle: "How daily stock totals and gradings reconcile into in / in-&-out / out flows", kicker: "Exchange · certified stocks", tone: "amber", updated: "2026-07-15", published: null, body: "CertifiedStocksMethodology" },
  { id: "options-expiry-and-the-itm-overhang", cat: "exchange", title: "Options expiry and the ITM overhang", subtitle: "55 expiries of history, the live countdown with the full board, and the ledger that turns each expiry into a datapoint", kicker: "Options · expiry mechanics", tone: "indigo", updated: "2026-08-16", published: "2026-08-17", body: "OptionsExpiryStudy" },
  { id: "the-gamma-map-where-hedging-stabilises-and-where-it-", cat: "exchange", title: "The gamma map — where hedging stabilises, and where it amplifies", subtitle: "Net dealer gamma by price level from every board's IV and OI: the flip point, the walls, and the vol-regime test", kicker: "Options · dealer gamma", tone: "indigo", updated: "2026-08-16", published: "2026-08-17", body: "OptionsGammaMap" },
  { id: "the-variance-risk-premium-what-implied-costs-vs-what", cat: "exchange", title: "The variance risk premium — what implied costs vs what realized delivers", subtitle: "ATM implied vs subsequent realized vol on every tracked board: no systematic premium in coffee, and where today's spread sits in the distribution", kicker: "Options · volatility", tone: "indigo", updated: "2026-08-17", published: "2026-08-17", body: "OptionsVrp" },
  { id: "the-25-delta-risk-reversal-what-the-wings-say-about-", cat: "exchange", title: "The 25-delta risk reversal — what the wings say about weather", subtitle: "Coffee's call-side skew reconstructed from every stored board: the frost calendar it trades on, the Uganda drought it tracked, and the alert ledger it feeds", kicker: "Options · skew", tone: "indigo", updated: "2026-08-17", published: "2026-08-17", body: "OptionsSkew" },
  { id: "options-flow-as-a-faster-cot-tested-swept-and-mostly", cat: "exchange", title: "Options flow as a faster COT — tested, swept, and mostly declined", subtitle: "Daily option OI against the weekly managed-money print: the price baseline that explains most of it, the sixteen-test sweep, and the live price-implied nowcast", kicker: "Options · positioning", tone: "indigo", updated: "2026-08-17", published: "2026-08-17", body: "OptionsFlowCot" },
  { id: "oi-walls-where-the-strike-matrix-defends-a-level", cat: "exchange", title: "OI walls — where the strike matrix defends a level", subtitle: "Call walls above, put walls below: the crossing test that holds in both markets, the falsification family that localises it, and the live map", kicker: "Options · OI walls", tone: "indigo", updated: "2026-08-17", published: "2026-08-17", body: "OptionsOiWalls" },
  { id: "the-optionization-ratio-coffee-s-risk-is-moving-into", cat: "exchange", title: "The optionization ratio — coffee's risk is moving into the options book", subtitle: "KC crossed parity this year: more option OI than futures OI on the front complex — and a delta-equivalent book our futures-only COT feed cannot see", kicker: "Options · market structure", tone: "indigo", updated: "2026-08-17", published: "2026-08-17", body: "OptionsOptionization" },
  { id: "the-conilon-reference-stack-cooabriel-cepea-vit-ria-", cat: "exchange", title: "The conilon reference stack — Cooabriel, CEPEA, Vitória and the B3 future", subtitle: "Four prices for the same coffee: what separates them, how much is fixed cost vs percentage of the price, and how wide the gap runs", kicker: "Basis · conilon references", tone: "teal", updated: "2026-08-12", published: "2026-08-12", body: "ConilonBasis" },
  { id: "tender-parity-tool", cat: "exchange", title: "Tender-parity tool", subtitle: "Cost-stack vs the exchange, origin gradings, and the parity→inflow study", kicker: "Exchange · tender parity", tone: "sky", updated: "2026-07-15", published: null, body: "CertifiedStocksParity" },
  { id: "contract-rules", cat: "exchange", title: "Contract Rules", subtitle: null, kicker: null, tone: null, updated: null, published: null, body: "ContractRules" },
  { id: "robusta-delivery-the-ice-tender-settlement-process", cat: "exchange", title: "Robusta delivery — the ICE tender & settlement process", subtitle: "How a short tenders, how longs are allocated, and how cash & warrants settle (ICE Clear Europe Part P)", kicker: "Contract rules · Delivery", tone: "emerald", updated: "2026-07-15", published: null, body: "DeliveryProcessMethodology" },
  { id: "beyond-the-hockey-stick-an-s-curve-model-for-emergin", cat: "demand", title: "Beyond the hockey stick: an S-curve model for emerging-market coffee demand", subtitle: "Logistic growth fitted per market instead of naive linear extrapolation", kicker: "Demand · Forecasting Methodology", tone: "rose", updated: null, published: null, body: "DemandArticles" },
  { id: "k-table-for-our-12-markets-proposed-ceilings-the-log", cat: "demand", title: "K table for our 12 markets — proposed ceilings & the logic behind each", subtitle: "Per-market saturation ceilings with the reasoning behind every K", kicker: "Demand · Proposed Saturation Ceilings (K)", tone: "rose", updated: null, published: null, body: "DemandArticles" },
  { id: "the-ceiling-k-the-retail-multiplier-and-where-the-an", cat: "demand", title: "The ceiling (K), the retail multiplier, and where the analogy breaks", subtitle: "What bounds K — culture, demographics, price — and how it can shift", kicker: "Demand · Saturation & Risk", tone: "rose", updated: null, published: null, body: "DemandArticles" },
  { id: "demand-data-indices-the-reconciliation-and-concentra", cat: "demand", title: "Demand data & indices — the reconciliation and concentration math", subtitle: "The smaller indices behind the import, consumption and spot panels", kicker: "Demand · Data methods", tone: "rose", updated: "2026-07-14", published: null, body: "DemandDataMethodology" },
  { id: "honduras-origin-country-profile", cat: "supply", title: "Honduras — origin country profile", subtitle: "Six regions, 73k growers and a 2× yield spread: what the 2021 dossier says, and which of its numbers survive checking", kicker: "Origin profile · Honduras", tone: "emerald", updated: "2026-08-25", published: "2026-08-25", body: "HondurasProfile" },
  { id: "workflow-failure-taxonomy", cat: "admin", title: "A failed workflow is not a failed system", subtitle: "847 red runs, taken apart \u2014 most are a pre-merge gate working, a workflow that no longer exists, or a freshness check exiting non-zero because it found exactly what it was built to find", kicker: "Platform \u00b7 reliability", tone: "slate", updated: "2026-09-04", published: "2026-09-04", body: "WorkflowFailures" },
  { id: "vietnam-mid-month-customs-bulletin", cat: "supply", title: "Is the mid-month customs number half a month?", subtitle: "Vietnam publishes a first-half export bulletin two weeks before the month closes. The trade doubles it. Twenty-four paired months say what that actually costs you", kicker: "Vietnam \u00b7 Customs bulletins", tone: "amber", updated: "2026-08-28", published: "2026-08-28", body: "VnMidMonth" },
  { id: "cert-stocks-and-the-front-spread", cat: "exchange", title: "Certified stocks and the front spread — does the textbook hold?", subtitle: "The scatter every broker publishes, rebuilt on our own five years of contract boards — and checked in halves, which is where the two markets part company", kicker: "Curve structure · Theory of storage", tone: "sky", updated: "2026-08-26", published: "2026-08-26", body: "CertStocksSpread" },
];
